export const services = [
    {
      id: 1,
      title: 'Full Hair Color',
      description: 'Complete color coverage for a consistent and vibrant look.',
      imageUrl: 'images/services/service1.jpg',
    },
    {
      id: 2,
      title: 'Highlights',
      description: 'Lighten selected sections of hair for a bright and blended look.',
      imageUrl: 'images/services/service2.jpg',
    },
    {
      id: 3,
      title: 'Partial Highlights',
      description: 'Highlights applied to specific sections for a natural look.',
      imageUrl: 'images/services/service3.jpg',
    },
    {
      id: 4,
      title: 'Balayage',
      description: 'Natural sun-kissed highlights with a smooth, hand-painted technique.',
      imageUrl: 'images/services/service4.jpg',
    },
    {
      id: 5,
      title: 'Ombre',
      description: 'Gradual fade from dark roots to light ends, creating a beautiful transition.',
      imageUrl: 'images/services/service5.jpg',
    },
    {
      id: 6,
      title: 'Sombre (Soft Ombre)',
      description: 'A softer, more subtle version of ombre for a natural transition.',
      imageUrl: 'images/services/service6.jpg',
    },
    {
      id: 7,
      title: 'Lowlights',
      description: 'Adding darker shades to certain strands for depth and contrast.',
      imageUrl: 'images/services/service7.jpg',
    },
    {
      id: 8,
      title: 'Root Touch-Up',
      description: 'Color application to new hair growth for consistent color coverage.',
      imageUrl: 'images/services/service8.jpg',
    },
    {
      id: 9,
      title: 'Glossing Treatment',
      description: 'Adds shine and refreshes color for a vibrant finish.',
      imageUrl: 'images/services/service9.jpg',
    },
    {
      id: 10,
      title: 'Hair Tinting',
      description: 'Temporary or semi-permanent color to adjust tone and add shine.',
      imageUrl: 'images/services/service10.jpg',
    },
    {
      id: 11,
      title: 'Babylights',
      description: 'Very fine highlights that mimic natural, sun-lit highlights.',
      imageUrl: 'images/services/service11.jpg',
    },
    {
      id: 12,
      title: 'Color Correction',
      description: 'Correcting unwanted tones or uneven color for a fresh start.',
      imageUrl: 'images/services/service12.jpg',
    },
    {
      id: 13,
      title: 'Fantasy Colors',
      description: 'Bright, bold colors for creative and high-fashion looks.',
      imageUrl: 'images/services/service13.jpg',
    },
    {
      id: 14,
      title: 'Double Process Color',
      description: 'Bleaching followed by color application for vibrant results.',
      imageUrl: 'images/services/service14.jpg',
    },
    {
      id: 15,
      title: 'Highlights/Lowlights Combo',
      description: 'Combining highlights and lowlights for a multi-dimensional look.',
      imageUrl: 'images/services/service15.jpg',
    },
    {
      id: 16,
      title: 'Shadow Root',
      description: 'Blending root color with the rest of the hair for a natural transition.',
      imageUrl: 'images/services/service16.jpg',
    },
    {
      id: 17,
      title: 'Toner',
      description: 'Adjusts undertones and neutralizes brassiness for a perfect shade.',
      imageUrl: 'images/services/service17.jpg',
    },
    {
      id: 18,
      title: 'Hair Contouring',
      description: 'Strategically placed highlights and lowlights to enhance facial features.',
      imageUrl: 'images/services/service18.jpg',
    },
];
  